name: Build

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --tag planpilot-service:ci .
